[package]
name = "night_market"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.5"
# clipboard = "0.5"

[profile.release]
strip = true
opt-level = "s"
lto = true
codegen-units = 1
